// features/layouts/components/nav-icons.ts

import {
  LayoutDashboard,
  CalendarDays,
  CalendarRange,
  CreditCard,
  Store,
  Users,
  FileText,
  ShieldCheck,
  BarChart3,
  Package,
  ClipboardList,
  CalendarHeart,
  UserCircle,
  Clock,
  Truck,
  Settings,
  UserCog,
  Home,
  BookOpen,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const NAV_ICONS: Record<string, LucideIcon> = {
  LayoutDashboard,
  CalendarDays,
  CalendarRange,
  CreditCard,
  Store,
  Users,
  FileText,
  ShieldCheck,
  BarChart3,
  Package,
  ClipboardList,
  CalendarHeart,
  UserCircle,
  Clock,
  Truck,
  Settings,
  UserCog,
  Home,
  BookOpen,
};
